management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
  endpoint:
    health:
      show-details: when-authorized

spring:
  datasource:
    url: ${vcap.services.lms-hdi.credentials.url}
    username: ${vcap.services.lms-hdi.credentials.user}
    password: ${vcap.services.lms-hdi.credentials.password}
    driver-class-name: com.sap.db.jdbc.Driver
  jpa:
    properties:
      ddl-auto: none
      dialect: org.hibernate.dialect.HANAColumnStoreDialect
      hibernate:
        default_schema: ${vcap.services.lms-hdi.credentials.schema}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: dev



