logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
  endpoint:
    health:
      show-details: always

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-local.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/lmsDb
    username: ${postgresUser}
    password: ${postgresPassword}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect