logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.leverx.learning_management_system: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
  endpoint:
    health:
      show-details: always


spring:
  h2:
    console:
     enabled: true
  path: /h2-console
  datasource:
    url: jdbc:h2:mem:lms
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect