
mailtrap:
  token: ${MailToken}

logging:
  level:
    root: INFO
    javax.management.remote.rmi: WARN
    sun.rmi: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
  endpoint:
    health:
      show-details: always

spring:
  h2:
    console:
     enabled: true
  path: /h2-console
  datasource:
    url: jdbc:h2:mem:learning_management_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect