spring:
  jpa:
    open-in-view: false
  profiles:
    active: local
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

