spring:
  jpa:
   open-in-view: false
  profiles:
    active: local
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

mailtrap:
  token: ${MailToken}
  id: ${inboxid}

management:
  endpoints:
    web:
#      base-path: /api/actuator


