databaseChangeLog:
  - changeSet:
      id: create-course-settings-table
      author: Giorgi
      changes:
        - createTable:
            tableName: course_settings
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    nullable: false
                    primaryKey: true
              - column:
                  name: start_date
                  type: TIMESTAMP
              - column:
                  name: end_date
                  type: TIMESTAMP
              - column:
                  name: is_public
                  type: BOOLEAN
